const mongoose=require('mongoose')
const cartSchema=mongoose.Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        required:true
    },
    items:[{
        product:{
        type:mongoose.Types.ObjectId,
        ref:'Product',
        required:true
    },
        price:{
            type:Number,
            ref:'Product',
            required:true
        },
        quantity:{
            type:Number,
            required:true
        }
    }],
    totalPrice:{
        type:Number,
        default:0
    },
    time:{
        type:Date,
        default:Date.now
    }
});
module.exports=mongoose.model('Cart',cartSchema)